<a href="https://colab.research.google.com/github/dhruv-kachhadiya/Google-Colab-TensorFlow/blob/main/prac_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
hello = tf.constant("hello")
world = tf.constant("world")

In [6]:
tf.print(hello+" "+world)

hello world


In [8]:
tf.fill([2,3],1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [9]:
ones_array = tf.ones([2,3])
zeros_array = tf.zeros([2,3])

In [11]:
tf.print(ones_array)

[[1 1 1]
 [1 1 1]]


In [12]:
tf.print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [27]:
randn = tf.random.normal([5,5],mean=2,stddev=0.1)
randu = tf.random.uniform([2,2],minval=10,maxval=20)

In [29]:
tf.print(randn)
print("\n")
tf.print(randu)

[[2.14381337 2.1683135 2.28431702 1.95973468 1.94953108]
 [2.01364541 2.00728464 1.95004344 2.04089403 1.96055114]
 [2.04595184 2.06450796 2.13466644 1.93177855 1.95034695]
 [1.9167707 1.8779 1.97916949 2.13322663 2.13930106]
 [2.1759696 2.15494943 1.95290935 2.04614735 1.7160387]]


[[16.2584267 18.8376884]
 [13.5923252 15.6066713]]


In [32]:
a = tf.constant([[10,20],[30,40]])
b = tf.constant([[100],[200]])

In [34]:
answer = tf.matmul(a,b)

In [35]:
print(answer)

tf.Tensor(
[[ 5000]
 [11000]], shape=(2, 1), dtype=int32)
